version: "3.9"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  db:
    image: postgres:10
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: application
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
volumes:
  db:

