default: &default
  adapter: postgresql
  host: 127.0.0.1
  username: application
  password: password 

production:
  adapter: postgresql
  encoding: utf8
  pool: 15
development:
  <<: *default
  database: dfc_development
test:
  <<: *default
  database: dfc_test
